// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DtetnP1nL8dOZ-bA6eUEKkFe1nZbido',
    appId: '1:58298262525:web:67bc4cc9d2bd740aa96f94',
    messagingSenderId: '58298262525',
    projectId: 'trywallsnow',
    authDomain: 'trywallsnow.firebaseapp.com',
    databaseURL: 'https://trywallsnow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trywallsnow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo3DeDIA53SgPeR-1kJ4_Sux1nFA9rOnE',
    appId: '1:58298262525:android:3faf3db599960490a96f94',
    messagingSenderId: '58298262525',
    projectId: 'trywallsnow',
    databaseURL: 'https://trywallsnow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trywallsnow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0Z-3HJvAg9Pus5UtRr1mtucsXOWDAF8',
    appId: '1:58298262525:ios:3edbde6e1bd9fdefa96f94',
    messagingSenderId: '58298262525',
    projectId: 'trywallsnow',
    databaseURL: 'https://trywallsnow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trywallsnow.appspot.com',
    iosBundleId: 'com.gauranshsharma.walls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB0Z-3HJvAg9Pus5UtRr1mtucsXOWDAF8',
    appId: '1:58298262525:ios:61cd7e8c3d0e6d62a96f94',
    messagingSenderId: '58298262525',
    projectId: 'trywallsnow',
    databaseURL: 'https://trywallsnow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trywallsnow.appspot.com',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DtetnP1nL8dOZ-bA6eUEKkFe1nZbido',
    appId: '1:58298262525:web:b9ba4b43c65d440ea96f94',
    messagingSenderId: '58298262525',
    projectId: 'trywallsnow',
    authDomain: 'trywallsnow.firebaseapp.com',
    databaseURL: 'https://trywallsnow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trywallsnow.appspot.com',
  );

}