// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9M9ChEQ8sYg-zVzsaqNGC2IkEpGFNh8',
    appId: '1:1077990734139:web:99feba0c1c834f200ddf1e',
    messagingSenderId: '1077990734139',
    projectId: 'walls-1809',
    authDomain: 'walls-1809.firebaseapp.com',
    storageBucket: 'walls-1809.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4poaj-EXSOVkvQaUCPzrsWKQWWbfyVmg',
    appId: '1:1077990734139:android:f92e86afc5d940a50ddf1e',
    messagingSenderId: '1077990734139',
    projectId: 'walls-1809',
    storageBucket: 'walls-1809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5gmfsPK3Dw2c0bvEwkqXAJ-gzad3oMcs',
    appId: '1:1077990734139:ios:02b8a24bc86fee6c0ddf1e',
    messagingSenderId: '1077990734139',
    projectId: 'walls-1809',
    storageBucket: 'walls-1809.appspot.com',
    iosBundleId: 'com.example.wallpaper',
  );
}
